import type { Property } from "@/types/property";

/**
 * DEMONSTRATION DATA. None of this is scraped from Zillow, Realtor.com,
 * Homes.com, another agent's site, or an MLS. Every entry is flagged with
 * isDemo so the UI can badge it clearly, and every image points at the
 * original PlaceholderImage component (see components/shared/PlaceholderImage.tsx)
 * rather than a photo. Replace via the PropertyProvider — see
 * docs/IDX-INTEGRATION.md.
 */
export const properties: Property[] = [
  {
    id: "demo-1",
    slug: "cabin-retreat-branford",
    status: "active",
    address: "Demonstration Address 1",
    city: "Branford",
    state: "FL",
    zipCode: "32008",
    price: 299900,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: null,
    acreage: 4.35,
    propertyType: "home",
    image: "/images/properties/placeholder.svg",
    altText: "Demonstration listing photo placeholder — cabin-style home on acreage",
    featured: true,
    description:
      "Demonstration listing: cabin-style home with room for land, a workshop, or animals. Replace with live MLS data via the PropertyProvider before launch.",
    latitude: null,
    longitude: null,
    listingAttribution: null,
    isDemo: true,
  },
  {
    id: "demo-2",
    slug: "family-home-lake-city",
    status: "active",
    address: "Demonstration Address 2",
    city: "Lake City",
    state: "FL",
    zipCode: "32055",
    price: 344900,
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 1607,
    acreage: 0.47,
    propertyType: "home",
    image: "/images/properties/placeholder.svg",
    altText: "Demonstration listing photo placeholder — single-family home",
    featured: true,
    description:
      "Demonstration listing: newer single-family home close to schools and shopping. Replace with live MLS data via the PropertyProvider before launch.",
    latitude: null,
    longitude: null,
    listingAttribution: null,
    isDemo: true,
  },
  {
    id: "demo-3",
    slug: "acreage-fort-white",
    status: "active",
    address: "Demonstration Address 3",
    city: "Fort White",
    state: "FL",
    zipCode: "32038",
    price: 259900,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1485,
    acreage: 7.95,
    propertyType: "home",
    image: "/images/properties/placeholder.svg",
    altText: "Demonstration listing photo placeholder — home on rural acreage",
    featured: false,
    description:
      "Demonstration listing: rural acreage property with a fenced yard and pole barn. Replace with live MLS data via the PropertyProvider before launch.",
    latitude: null,
    longitude: null,
    listingAttribution: null,
    isDemo: true,
  },
  {
    id: "demo-4",
    slug: "acreage-lake-butler",
    status: "active",
    address: "Demonstration Address 4",
    city: "Lake Butler",
    state: "FL",
    zipCode: "32054",
    price: 189900,
    bedrooms: null,
    bathrooms: null,
    squareFeet: null,
    acreage: 12,
    propertyType: "land",
    image: "/images/properties/placeholder.svg",
    altText: "Demonstration listing photo placeholder — vacant land and acreage",
    featured: false,
    description:
      "Demonstration listing: 12 acres of unimproved land, road access, no HOA. Replace with live MLS data via the PropertyProvider before launch.",
    latitude: null,
    longitude: null,
    listingAttribution: null,
    isDemo: true,
  },
  {
    id: "demo-5",
    slug: "manufactured-white-springs",
    status: "active",
    address: "Demonstration Address 5",
    city: "White Springs",
    state: "FL",
    zipCode: "32096",
    price: 249900,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1140,
    acreage: 5,
    propertyType: "manufactured",
    image: "/images/properties/placeholder.svg",
    altText: "Demonstration listing photo placeholder — manufactured home on acreage",
    featured: true,
    description:
      "Demonstration listing: manufactured home on 5 acres. Replace with live MLS data via the PropertyProvider before launch.",
    latitude: null,
    longitude: null,
    listingAttribution: null,
    isDemo: true,
  },
  {
    id: "demo-6",
    slug: "sold-jacksonville-home",
    status: "sold",
    address: "Demonstration Address 6",
    city: "Jacksonville",
    state: "FL",
    zipCode: "32219",
    price: null,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: null,
    acreage: null,
    propertyType: "home",
    image: "/images/properties/placeholder.svg",
    altText: "Demonstration listing photo placeholder — recently sold home",
    featured: false,
    description:
      "Demonstration listing: recently sold single-family home. Sale price withheld pending seller authorization. Replace with live MLS data via the PropertyProvider before launch.",
    latitude: null,
    longitude: null,
    listingAttribution: null,
    isDemo: true,
  },
  {
    id: "demo-7",
    slug: "new-construction-macclenny",
    status: "coming-soon",
    address: "Demonstration Address 7",
    city: "Macclenny",
    state: "FL",
    zipCode: "32063",
    price: 329900,
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 1820,
    acreage: 0.5,
    propertyType: "new-construction",
    image: "/images/properties/placeholder.svg",
    altText: "Demonstration listing photo placeholder — new construction home",
    featured: false,
    description:
      "Demonstration listing: new construction, builder warranty, move-in ready soon. Replace with live MLS data via the PropertyProvider before launch.",
    latitude: null,
    longitude: null,
    listingAttribution: null,
    isDemo: true,
  },
  {
    id: "demo-8",
    slug: "investment-duplex-jacksonville",
    status: "active",
    address: "Demonstration Address 8",
    city: "Jacksonville",
    state: "FL",
    zipCode: "32206",
    price: 279900,
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 1960,
    acreage: 0.18,
    propertyType: "investment",
    image: "/images/properties/placeholder.svg",
    altText: "Demonstration listing photo placeholder — duplex investment property",
    featured: false,
    description:
      "Demonstration listing: duplex, two rented units. Replace with live MLS data via the PropertyProvider before launch.",
    latitude: null,
    longitude: null,
    listingAttribution: null,
    isDemo: true,
  },
];
